swagger: "2.0"
info:
  title: Cloud-AI-API
  version: 1.0.0
paths:
  /v1/user/{user_id}:
    get:
      operationId: "getUserById"
      x-google-backend:
        address: https://user-232730424282.us-central1.run.app
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Successful response"
    put:
      operationId: "updateUserById"
      x-google-backend:
        address: https://user-232730424282.us-central1.run.app
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Successful response"
    delete:
      operationId: "deleteUserById"
      x-google-backend:
        address: https://user-232730424282.us-central1.run.app
      parameters:
        - name: user_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Successful response"
  /v1/user:
    post:
      operationId: "createUser"
      x-google-backend:
        address: https://user-232730424282.us-central1.run.app
      responses:
        200:
          description: "Successful response"
